### ISSUE TITLE
flathub verification?

### ISSUE THREAD

**Issue by qoijjj** [flathub/com.unicornsonlsd.finamp#5]
Thank you for publishing this on flathub!

Getting verification would allow an increased level of user trust.

https://docs.flathub.org/docs/for-app-authors/verification#im-publishing-an-app-on-flathub-how-do-i-get-it-verified

This would require the blessing of upstream devs.

**Comment by baarkerlounger** [comment]
@jmshrv is on board I believe. Just need the token adding on the domain.

**Comment by jmshrv** [comment]
I'd like to verify this, is there a way for me to get the token or does the original uploader need to send it to me?

**Comment by baarkerlounger** [comment]
I'm not sure. @hfiguiere @bbhtt is it possible to add @jmshrv to this repo so they can see Finamp in their developer portal on Flathub?

**Comment by bbhtt** [comment]
> I'm not sure. @hfiguiere @bbhtt is it possible to add @jmshrv to this repo so they can see Finamp in their developer portal on Flathub?

Open an issue https://docs.flathub.org/docs/for-app-authors/maintenance#maintainer-access-to-flathub-application-repository

**Comment by baarkerlounger** [comment]
Ah thank you, will do that. @jmshrv can you confirm you'd like to be added? @Chaphasilor maybe as well?

**Comment by Chaphasilor** [comment]
@baarkerlounger yes, please add both of us :)

**Comment by jmshrv** [comment]
I'd like to be added :)

**Comment by Chaphasilor** [comment]
I've accepted the invitation and logged into Flathub using my GitHub account, but the developer portal is empty for me. Does it simply take some time, or are additional steps required? 🤔

**Comment by bbhtt** [comment]
You have to wait for a bit and hit the refresh button on the page there https://docs.flathub.org/docs/for-app-authors/submission#i-cant-see-the-app-in-my-authored-apps-on-the-developer-portal-why
